### ISSUE TITLE
Re-disabling with different options makes for jumpy scroll

### ISSUE THREAD

**Issue by Noino** [realjoshharrison/jquery-disablescroll#2]
I found that disabling scroll with default options on load, and re-disabling with `handleScrollbar=false` for the duration of animate to then re-re-disable completely makes the page simply skip the animation part and jump to where it was going.
Calling undo before re-disable fixes the problem, which made me discover another quality of life improvement. Chaining can't be done.
Added a `return this` to the end of `$.fn.disablescroll = function(method) {` in my local copy for now.

**Comment by ultrapasty** [comment]
You're right, there's no reason it shouldn't `return this`. I'll add this when I get a chance.

**Comment by melloware** [comment]
@realjoshharrison Any updates on this or the PR you have waiting?
